.

diff --git a/.github/workflows/shared-terraform-plan.yaml b/.github/workflows/shared-terraform-plan.yaml
--- a/.github/workflows/shared-terraform-plan.yaml
+++ b/.github/workflows/shared-terraform-plan.yaml
@@ -127,6 +127,9 @@ jobs:
           TF_TOKEN_APP_TERRAFORM_IO: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
           TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
         run: |
+          set +e  # Disable immediate exit on error to handle errors gracefully
+          status=0
+
           # Build terraform plan command based on vars file and SOPS usage
           cmd="terraform plan -no-color -input=false"
 
@@ -151,21 +154,17 @@ jobs:
           echo "Terraform command: $cmd"
 
           start=$(date +%s)
-
-          # handle errors and capture output
-          set +e
-          docker compose run $cmd 2>&1 | tee tf.console.txt
+          # Run terraform plan and capture output
+          docker compose run --rm $cmd 2>&1 | tee tf.console.txt
           status=${PIPESTATUS[0]}
-          set -e
-
           end=$(date +%s)
 
           echo "duration=$((end - start))" >> $GITHUB_OUTPUT
           echo "cmd=$cmd" >> $GITHUB_OUTPUT
 
           if [ $status -ne 0 ]; then
-            echo "Terraform plan failed."
-            exit 1
+            echo "Terraform apply failed"
+            exit $status
           fi
 
       - name: Format Terraform Plan Diff
